spring:

  autoconfigure:
    exclude:
      # get rid of "Using default security password" logs and basic auth defaults
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration



app.auth:
  # e.g.: https://<your_domain>.eu.auth0.com/.well-known/jwks.json
  jwksUri: http://localhost:9000/.well-known/jwks.json
  acceptIssuers:
    - "https://my-issuer-1.local"
  acceptAudiences:
    - "my-audience-1"
    - "my-audience-2"
